### ISSUE TITLE
Help?11 Magma Blocks broke!

### ISSUE THREAD

**Issue by YourFellow2467** [VortexParadox/TF2_ResourcePack#4]
So I was stroking my genius as usual and i went to the nether throgh my epik nether portel, but then i saw flamethrowers every where! what do?``

**Comment by VortexParadox** [comment]
Have you tried restarting your machine?
Maybe system32 is the issue, try renaming it to system31 so it gets downgraded.

**Comment by scoliono** [comment]
#7 fixes this.
